---
openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/TRISTAN_9/NABDemo/1.0.0

info:
  description: NAB demo calls API
  version: "1.0.0"
  title: NAB demo calls API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

paths:
  /battery:
    post:
      parameters:
        - in: query
          name: serviceID
          description: the ID of the available metarex service
          required: false
          schema:
            type: string
      summary: convert a battery percentage to an image
      operationId: batteryToPNG
      description: convert a battery percentage to an image
      responses:
        "200":
          description: auto elt completed
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/batteryFormat"
        description: battery to PNG
  /batteryStagger:
    post:
      parameters:
        - in: query
          name: serviceID
          description: the ID of the available metarex service
          required: false
          schema:
            type: string
      summary: convert a battery percentage to an image
      operationId: batteryToPNGe
      description: convert a battery percentage to an image
      responses:
        "200":
          description: auto elt completed
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/batteryFormat"
        description: battery to PNG
  /batteryFault:
    post:
      summary: convert a battery percentage to an image
      operationId: batteryToJPEG
      description: convert a battery percentage to an image
      responses:
        "200":
          description: auto elt completed
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/batteryFormat"
        description: battery to JPEG
  /gps:
    post:
      summary: convert gps xml to json
      operationId: gps
      description: convert gps xml to json
      responses:
        "200":
          description: auto elt completed
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/xml:
            schema:
              type: object
        description: xml to json
  /ninjsToMD:
    post:
      summary: convert ninjs to markdown
      operationId: ninjsmd
      description: convert ninjs to markdown
      responses:
        "200":
          description: auto elt completed
          content:
            application/json:
              schema:
                type: object
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: json to markdown
  /mxfContents:
    post:
      summary: extract the header metadata from an MRX file
      operationId: mxfExtract
      description: extract the header metadata from an MRX file as JSON
      responses:
        "200":
          description: header extraction completed
          content:
            application/json:
              schema:
                type: object
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
        description: MXF file
  /ffmpeg:
    post:
      summary: rnf csv to the ffmpeg actions that created it
      operationId: rnffmpeg
      description: extract the metadata from the csv to create the values
      responses:
        "200":
          description: ffmpeg generated
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          text/csv:
            schema:
              type: string
        description: rnf csv format
  /ninjsToNewsml:
    post:
      summary: ninjs to Newsml
      operationId: NinjsToNewsml
      description: manually convert ninjs to ffmpeg
      responses:
        "200":
          description: newsml generated
          content:
            application/xml:
              schema:
                type: object
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: ninjs
  /C2PAExtract:
    post:
      summary: jpeg c2pa extraction
      operationId: jpeg2c2pa
      description: extract c2pa metadata as a service
      responses:
        "200":
          description: c2pa metadata extracted
          content:
            application/json:
              schema:
                type: object
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
        description: wav sound file
  /waveform:
    post:
      summary: audio to png visualisation
      operationId: soundwave
      description: audio to png visualisation
      responses:
        "200":
          description: image generated
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          audio/wav:
            schema:
              type: string
              format: binary
        description: jpeg image
  /qcToGraph:
    post:
      summary: xml to png graph visualisation
      operationId: tograph
      description: xml to graph visualisation
      responses:
        "200":
          description: image generated
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: "invalid input, object invalid"
      requestBody:
        content:
          application/xml:
            schema:
              type: object
        description: xml qc report

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    batteryFormat:
      type: object
      additionalProperties: false
      properties:
        percentage:
          type: number
          minimum: 0
          maximum: 100
        status:
          type: string
