import type { DemoSource, MrxETLService, MrxRegisterCache } from '$lib/nabTypes';

import gpx from '$lib/reg/MRX.123.456.789.gpx/register.json';
import wav from '$lib/reg/MRX.123.456.789.wav/register.json';

export const fetchList = [
{type: "gpx", id: "Alt_Portsmouth", url: "demo03/Alt_Portsmouth.gpx" },
{type: "gpx", id: "Basel_StBrevin_Eurovelo6", url: "demo03/Basel_St-Brevin_Eurovelo6.gpx" },
{type: "wav", id: "CommonBlackbirdshort", url: "demo03/Common Blackbird - short.wav" },
{type: "wav", id: "CommonChiffchaffshort", url: "demo03/Common Chiffchaff - short.wav" },
{type: "gpx", id: "Courgenay_BallonDAlsace", url: "demo03/Courgenay_Ballon-DAlsace.gpx" },
{type: "gpx", id: "Dole_Langres", url: "demo03/Dole_Langres.gpx" },
{type: "gpx", id: "Dole_SalinlesBains", url: "demo03/Dole_Salin-les-Bains.gpx" },
{type: "wav", id: "EurasianBlackcapshort", url: "demo03/Eurasian Blackcap - short.wav" },
{type: "wav", id: "EurasianWrenshort", url: "demo03/Eurasian Wren - short.wav" },
{type: "wav", id: "EuropeanRobinshort", url: "demo03/European Robin - short.wav" },
{type: "gpx", id: "JuraRoute72011", url: "demo03/JuraRoute72011.gpx" },
{type: "gpx", id: "MoselradwegAusWiki", url: "demo03/MoselradwegAusWiki.gpx" },
{type: "gpx", id: "Newhaven_Brighton", url: "demo03/Newhaven_Brighton.gpx" },
{type: "gpx", id: "Ouistreham_Caen", url: "demo03/Ouistreham_Caen.gpx" },
{type: "gpx", id: "ReimsVitryLeFrancois", url: "demo03/Reims-VitryLeFrancois.gpx" },
{type: "gpx", id: "SalinslesBains_Fleurier", url: "demo03/Salins-les-Bains_Fleurier.gpx" },
{type: "gpx", id: "Serqueaux_Dieppe", url: "demo03/Serqueaux_Dieppe.gpx" },
{type: "wav", id: "SongThrushshort", url: "demo03/Song Thrush - short.wav" },
{type: "gpx", id: "Southampton_Portsmouth", url: "demo03/Southampton_Portsmouth.gpx" },
{type: "gpx", id: "VitryleFrancois_Langres", url: "demo03/Vitry-le-Francois_Langres.gpx" },
{type: "gpx", id: "VoieVerteHauteVosges", url: "demo03/VoieVerteHauteVosges.gpx" },
]

export const regCache:MrxRegisterCache = [
{mrxId: "MRX.123.456.789.gpx", reg: gpx},
{mrxId: "MRX.123.456.789.wav", reg: wav},
]

export const dataCache = [
{type: "gpx", id:"Alt_Portsmouth", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Alt_Portsmouth", outputMRXID:"toW3C" }},
{type: "gpx", id:"Basel_StBrevin_Eurovelo6", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Basel_StBrevin_Eurovelo6", outputMRXID:"toW3C" }},
{type: "wav", id:"CommonBlackbirdshort", post: {inputMRXID:"MRX.123.456.789.wav", data: "CommonBlackbirdshort", outputMRXID:"ToWaveform" }},
{type: "wav", id:"CommonChiffchaffshort", post: {inputMRXID:"MRX.123.456.789.wav", data: "CommonChiffchaffshort", outputMRXID:"ToWaveform" }},
{type: "gpx", id:"Courgenay_BallonDAlsace", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Courgenay_BallonDAlsace", outputMRXID:"toW3C" }},
{type: "gpx", id:"Dole_Langres", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Dole_Langres", outputMRXID:"toW3C" }},
{type: "gpx", id:"Dole_SalinlesBains", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Dole_SalinlesBains", outputMRXID:"toW3C" }},
{type: "wav", id:"EurasianBlackcapshort", post: {inputMRXID:"MRX.123.456.789.wav", data: "EurasianBlackcapshort", outputMRXID:"ToWaveform" }},
{type: "wav", id:"EurasianWrenshort", post: {inputMRXID:"MRX.123.456.789.wav", data: "EurasianWrenshort", outputMRXID:"ToWaveform" }},
{type: "wav", id:"EuropeanRobinshort", post: {inputMRXID:"MRX.123.456.789.wav", data: "EuropeanRobinshort", outputMRXID:"ToWaveform" }},
{type: "gpx", id:"JuraRoute72011", post: {inputMRXID:"MRX.123.456.789.gpx", data: "JuraRoute72011", outputMRXID:"toW3C" }},
{type: "gpx", id:"MoselradwegAusWiki", post: {inputMRXID:"MRX.123.456.789.gpx", data: "MoselradwegAusWiki", outputMRXID:"toW3C" }},
{type: "gpx", id:"Newhaven_Brighton", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Newhaven_Brighton", outputMRXID:"toW3C" }},
{type: "gpx", id:"Ouistreham_Caen", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Ouistreham_Caen", outputMRXID:"toW3C" }},
{type: "gpx", id:"ReimsVitryLeFrancois", post: {inputMRXID:"MRX.123.456.789.gpx", data: "ReimsVitryLeFrancois", outputMRXID:"toW3C" }},
{type: "gpx", id:"SalinslesBains_Fleurier", post: {inputMRXID:"MRX.123.456.789.gpx", data: "SalinslesBains_Fleurier", outputMRXID:"toW3C" }},
{type: "gpx", id:"Serqueaux_Dieppe", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Serqueaux_Dieppe", outputMRXID:"toW3C" }},
{type: "wav", id:"SongThrushshort", post: {inputMRXID:"MRX.123.456.789.wav", data: "SongThrushshort", outputMRXID:"ToWaveform" }},
{type: "gpx", id:"Southampton_Portsmouth", post: {inputMRXID:"MRX.123.456.789.gpx", data: "Southampton_Portsmouth", outputMRXID:"toW3C" }},
{type: "gpx", id:"VitryleFrancois_Langres", post: {inputMRXID:"MRX.123.456.789.gpx", data: "VitryleFrancois_Langres", outputMRXID:"toW3C" }},
{type: "gpx", id:"VoieVerteHauteVosges", post: {inputMRXID:"MRX.123.456.789.gpx", data: "VoieVerteHauteVosges", outputMRXID:"toW3C" }},
]

export const sources: DemoSource[] = [
{
		id: "Alt_Portsmouth",
		mrxId: "MRX.123.456.789.gpx",
		name: "Alt_Portsmouth.gpx",
		clip: "",
		srcUrl: "demo03/Alt_Portsmouth.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "Basel_StBrevin_Eurovelo6",
		mrxId: "MRX.123.456.789.gpx",
		name: "Basel_St-Brevin_Eurovelo6.gpx",
		clip: "",
		srcUrl: "demo03/Basel_St-Brevin_Eurovelo6.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "CommonBlackbirdshort",
		mrxId: "MRX.123.456.789.wav",
		name: "Common Blackbird - short.wav",
		clip: "",
		srcUrl: "demo03/Common Blackbird - short.wav",
		summary: "",
		srcReg: "wav",
		xtra: [],
	  },
{
		id: "CommonChiffchaffshort",
		mrxId: "MRX.123.456.789.wav",
		name: "Common Chiffchaff - short.wav",
		clip: "",
		srcUrl: "demo03/Common Chiffchaff - short.wav",
		summary: "",
		srcReg: "wav",
		xtra: [],
	  },
{
		id: "Courgenay_BallonDAlsace",
		mrxId: "MRX.123.456.789.gpx",
		name: "Courgenay_Ballon-DAlsace.gpx",
		clip: "",
		srcUrl: "demo03/Courgenay_Ballon-DAlsace.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "Dole_Langres",
		mrxId: "MRX.123.456.789.gpx",
		name: "Dole_Langres.gpx",
		clip: "",
		srcUrl: "demo03/Dole_Langres.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "Dole_SalinlesBains",
		mrxId: "MRX.123.456.789.gpx",
		name: "Dole_Salin-les-Bains.gpx",
		clip: "",
		srcUrl: "demo03/Dole_Salin-les-Bains.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "EurasianBlackcapshort",
		mrxId: "MRX.123.456.789.wav",
		name: "Eurasian Blackcap - short.wav",
		clip: "",
		srcUrl: "demo03/Eurasian Blackcap - short.wav",
		summary: "",
		srcReg: "wav",
		xtra: [],
	  },
{
		id: "EurasianWrenshort",
		mrxId: "MRX.123.456.789.wav",
		name: "Eurasian Wren - short.wav",
		clip: "",
		srcUrl: "demo03/Eurasian Wren - short.wav",
		summary: "",
		srcReg: "wav",
		xtra: [],
	  },
{
		id: "EuropeanRobinshort",
		mrxId: "MRX.123.456.789.wav",
		name: "European Robin - short.wav",
		clip: "",
		srcUrl: "demo03/European Robin - short.wav",
		summary: "",
		srcReg: "wav",
		xtra: [],
	  },
{
		id: "JuraRoute72011",
		mrxId: "MRX.123.456.789.gpx",
		name: "JuraRoute72011.gpx",
		clip: "",
		srcUrl: "demo03/JuraRoute72011.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "MoselradwegAusWiki",
		mrxId: "MRX.123.456.789.gpx",
		name: "MoselradwegAusWiki.gpx",
		clip: "",
		srcUrl: "demo03/MoselradwegAusWiki.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "Newhaven_Brighton",
		mrxId: "MRX.123.456.789.gpx",
		name: "Newhaven_Brighton.gpx",
		clip: "",
		srcUrl: "demo03/Newhaven_Brighton.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "Ouistreham_Caen",
		mrxId: "MRX.123.456.789.gpx",
		name: "Ouistreham_Caen.gpx",
		clip: "",
		srcUrl: "demo03/Ouistreham_Caen.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "ReimsVitryLeFrancois",
		mrxId: "MRX.123.456.789.gpx",
		name: "Reims-VitryLeFrancois.gpx",
		clip: "",
		srcUrl: "demo03/Reims-VitryLeFrancois.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "SalinslesBains_Fleurier",
		mrxId: "MRX.123.456.789.gpx",
		name: "Salins-les-Bains_Fleurier.gpx",
		clip: "",
		srcUrl: "demo03/Salins-les-Bains_Fleurier.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "Serqueaux_Dieppe",
		mrxId: "MRX.123.456.789.gpx",
		name: "Serqueaux_Dieppe.gpx",
		clip: "",
		srcUrl: "demo03/Serqueaux_Dieppe.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "SongThrushshort",
		mrxId: "MRX.123.456.789.wav",
		name: "Song Thrush - short.wav",
		clip: "",
		srcUrl: "demo03/Song Thrush - short.wav",
		summary: "",
		srcReg: "wav",
		xtra: [],
	  },
{
		id: "Southampton_Portsmouth",
		mrxId: "MRX.123.456.789.gpx",
		name: "Southampton_Portsmouth.gpx",
		clip: "",
		srcUrl: "demo03/Southampton_Portsmouth.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "VitryleFrancois_Langres",
		mrxId: "MRX.123.456.789.gpx",
		name: "Vitry-le-Francois_Langres.gpx",
		clip: "",
		srcUrl: "demo03/Vitry-le-Francois_Langres.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
{
		id: "VoieVerteHauteVosges",
		mrxId: "MRX.123.456.789.gpx",
		name: "VoieVerteHauteVosges.gpx",
		clip: "",
		srcUrl: "demo03/VoieVerteHauteVosges.gpx",
		summary: "",
		srcReg: "gpx",
		xtra: [],
	  },
]
