import type { DemoSource, MrxETLService, MrxRegisterCache } from '$lib/nabTypes';

import njs from '$lib/reg/MRX.123.456.789.njs/register.json';

export const fetchList = [
{type: "json", id: "SIPA_image_2", url: "demo10/SIPA_image_2.json" },
{type: "json", id: "ap_audio", url: "demo10/ap_audio.json" },
{type: "json", id: "ap_image", url: "demo10/ap_image.json" },
{type: "json", id: "ap_video", url: "demo10/ap_video.json" },
{type: "json", id: "businesswirenewsml20130605006126", url: "demo10/businesswire-newsml-20130605006126.json" },
{type: "json", id: "businesswirenewsml20130731006140", url: "demo10/businesswire-newsml-20130731006140.json" },
{type: "json", id: "dpa_text", url: "demo10/dpa_text.json" },
{type: "json", id: "imageEncodedRights", url: "demo10/imageEncodedRights.json" },
{type: "json", id: "imageLinkedRights", url: "demo10/imageLinkedRights.json" },
{type: "json", id: "ninjsExSimpleText_2", url: "demo10/ninjsExSimpleText_2.json" },
{type: "json", id: "ntb_text", url: "demo10/ntb_text.json" },
{type: "json", id: "tt_text_image_2", url: "demo10/tt_text_image_2.json" },
]

export const regCache:MrxRegisterCache = [
{mrxId: "MRX.123.456.789.njs", reg: njs},
]

export const dataCache = [
{type: "json", id:"SIPA_image_2", post: {inputMRXID:"MRX.123.456.789.njs", data: "SIPA_image_2", outputMRXID:"toNewsML" }},
{type: "json", id:"ap_audio", post: {inputMRXID:"MRX.123.456.789.njs", data: "ap_audio", outputMRXID:"toNewsML" }},
{type: "json", id:"ap_image", post: {inputMRXID:"MRX.123.456.789.njs", data: "ap_image", outputMRXID:"toNewsML" }},
{type: "json", id:"ap_video", post: {inputMRXID:"MRX.123.456.789.njs", data: "ap_video", outputMRXID:"toNewsML" }},
{type: "json", id:"businesswirenewsml20130605006126", post: {inputMRXID:"MRX.123.456.789.njs", data: "businesswirenewsml20130605006126", outputMRXID:"toNewsML" }},
{type: "json", id:"businesswirenewsml20130731006140", post: {inputMRXID:"MRX.123.456.789.njs", data: "businesswirenewsml20130731006140", outputMRXID:"toNewsML" }},
{type: "json", id:"dpa_text", post: {inputMRXID:"MRX.123.456.789.njs", data: "dpa_text", outputMRXID:"toNewsML" }},
{type: "json", id:"imageEncodedRights", post: {inputMRXID:"MRX.123.456.789.njs", data: "imageEncodedRights", outputMRXID:"toNewsML" }},
{type: "json", id:"imageLinkedRights", post: {inputMRXID:"MRX.123.456.789.njs", data: "imageLinkedRights", outputMRXID:"toNewsML" }},
{type: "json", id:"ninjsExSimpleText_2", post: {inputMRXID:"MRX.123.456.789.njs", data: "ninjsExSimpleText_2", outputMRXID:"toNewsML" }},
{type: "json", id:"ntb_text", post: {inputMRXID:"MRX.123.456.789.njs", data: "ntb_text", outputMRXID:"toNewsML" }},
{type: "json", id:"tt_text_image_2", post: {inputMRXID:"MRX.123.456.789.njs", data: "tt_text_image_2", outputMRXID:"toNewsML" }},
]

export const sources: DemoSource[] = [
{
		id: "SIPA_image_2",
		mrxId: "MRX.123.456.789.njs",
		name: "SIPA_image_2.json",
		clip: "",
		srcUrl: "demo10/SIPA_image_2.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "ap_audio",
		mrxId: "MRX.123.456.789.njs",
		name: "ap_audio.json",
		clip: "",
		srcUrl: "demo10/ap_audio.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "ap_image",
		mrxId: "MRX.123.456.789.njs",
		name: "ap_image.json",
		clip: "",
		srcUrl: "demo10/ap_image.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "ap_video",
		mrxId: "MRX.123.456.789.njs",
		name: "ap_video.json",
		clip: "",
		srcUrl: "demo10/ap_video.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "businesswirenewsml20130605006126",
		mrxId: "MRX.123.456.789.njs",
		name: "businesswire-newsml-20130605006126.json",
		clip: "",
		srcUrl: "demo10/businesswire-newsml-20130605006126.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "businesswirenewsml20130731006140",
		mrxId: "MRX.123.456.789.njs",
		name: "businesswire-newsml-20130731006140.json",
		clip: "",
		srcUrl: "demo10/businesswire-newsml-20130731006140.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "dpa_text",
		mrxId: "MRX.123.456.789.njs",
		name: "dpa_text.json",
		clip: "",
		srcUrl: "demo10/dpa_text.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "imageEncodedRights",
		mrxId: "MRX.123.456.789.njs",
		name: "imageEncodedRights.json",
		clip: "",
		srcUrl: "demo10/imageEncodedRights.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "imageLinkedRights",
		mrxId: "MRX.123.456.789.njs",
		name: "imageLinkedRights.json",
		clip: "",
		srcUrl: "demo10/imageLinkedRights.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "ninjsExSimpleText_2",
		mrxId: "MRX.123.456.789.njs",
		name: "ninjsExSimpleText_2.json",
		clip: "",
		srcUrl: "demo10/ninjsExSimpleText_2.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "ntb_text",
		mrxId: "MRX.123.456.789.njs",
		name: "ntb_text.json",
		clip: "",
		srcUrl: "demo10/ntb_text.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
{
		id: "tt_text_image_2",
		mrxId: "MRX.123.456.789.njs",
		name: "tt_text_image_2.json",
		clip: "",
		srcUrl: "demo10/tt_text_image_2.json",
		summary: "",
		srcReg: "json",
		xtra: [],
	  },
]
